export const ARTIST_LIST_REQUEST = "ARTIST_LIST_REQUEST";
export const ARTIST_LIST_SUCCESS = "ARTIST_LIST_SUCCESS";
export const ARTIST_LIST_FAIL = "ARTIST_LIST_FAIL";

export const ARTIST_TAG_REQUEST = "ARTIST_TAG_REQUEST";
export const ARTIST_TAG_SUCCESS = "ARTIST_TAG_SUCCESS";
export const ARTIST_TAG_FAIL = "ARTIST_TAG_FAIL";

export const ARTIST_DETAILS_REQUEST = "ARTIST_DETAILS_REQUEST";
export const ARTIST_DETAILS_SUCCESS = "ARTIST_DETAILS_SUCCESS";
export const ARTIST_DETAILS_FAIL = "ARTIST_DETAILS_FAIL";

export const ARTIST_DELETE_REQUEST = "ARTIST_DELETE_REQUEST";
export const ARTIST_DELETE_SUCCESS = "ARTIST_DELETE_SUCCESS";
export const ARTIST_DELETE_FAIL = "ARTIST_DELETE_FAIL";

export const ARTIST_CREATE_REQUEST = "ARTIST_CREATE_REQUEST";
export const ARTIST_CREATE_SUCCESS = "ARTIST_CREATE_SUCCESS";
export const ARTIST_CREATE_FAIL = "ARTIST_CREATE_FAIL";
export const ARTIST_CREATE_RESET = "ARTIST_CREATE_RESET";

export const ARTIST_UPDATE_REQUEST = "ARTIST_UPDATE_REQUEST";
export const ARTIST_UPDATE_SUCCESS = "ARTIST_UPDATE_SUCCESS";
export const ARTIST_UPDATE_FAIL = "ARTIST_UPDATE_FAIL";
export const ARTIST_UPDATE_RESET = "ARTIST_UPDATE_RESET";
