export const SEND_CONTACT_EMAIL_REQUEST = "SEND_CONTACT_EMAIL_REQUEST";
export const SEND_CONTACT_EMAIL_SUCCESS = "SEND_CONTACT_EMAIL_SUCCESS";
export const SEND_CONTACT_EMAIL_FAIL = "SEND_CONTACT_EMAIL_FAIL";
export const SEND_CONTACT_EMAIL_RESET = "SEND_CONTACT_EMAIL_RESET";